stages:
  - test
sonarqube_master_job:
  stage: test
  script:
    - export ENCRYPT_KEY=`echo $CI_PROJECT_URL.git | md5sum | cut -d' ' -f1`
    - /opt/sonar-scanner-4.7.0/bin/sonar-scanner -Dsonar.sources=. -Dsonar.projectKey=p$ENCRYPT_KEY
